/**
 * vite-plugin-exif.ts
 *
 * Build-time Vite plugin that reads EXIF metadata from every image in
 * assets/img/ and writes the results to src/data/generatedExif.ts.
 *
 * This runs once when the Vite dev server starts and once at build time.
 * If a photo later gets proper GPS coordinates embedded, it will
 * automatically appear at the right location on the map after the next build.
 */

import type { Plugin } from 'vite'
import { promises as fs } from 'fs'
import path from 'path'
import exifr from 'exifr'

interface ExifEntry {
  lat?: number
  lng?: number
  date?: string
  make?: string
  model?: string
}

async function extractAndWrite(root: string) {
  const imgDir = path.join(root, 'assets', 'img')
  const outFile = path.join(root, 'src', 'data', 'generatedExif.ts')

  let files: string[]
  try {
    files = (await fs.readdir(imgDir)).filter((f) =>
      /\.(jpe?g|png|heic|webp)$/i.test(f),
    )
  } catch {
    return // assets/img doesn't exist yet during first install
  }

  const entries: Record<string, ExifEntry> = {}

  await Promise.all(
    files.map(async (file) => {
      try {
        const data = await exifr.parse(path.join(imgDir, file), {
          gps: true,
          pick: ['GPSLatitude', 'GPSLongitude', 'latitude', 'longitude',
                 'DateTimeOriginal', 'CreateDate', 'Make', 'Model'],
        })
        if (!data) return

        const entry: ExifEntry = {}
        if (data.latitude)  entry.lat = data.latitude
        if (data.longitude) entry.lng = data.longitude
        if (data.DateTimeOriginal || data.CreateDate) {
          const d = data.DateTimeOriginal ?? data.CreateDate
          entry.date = d instanceof Date
            ? d.toISOString().slice(0, 10)
            : String(d).slice(0, 10)
        }
        if (data.Make)  entry.make  = String(data.Make).trim()
        if (data.Model) entry.model = String(data.Model).trim()
        entries[file] = entry
      } catch {
        // Silently skip unreadable files
      }
    }),
  )

  const body = JSON.stringify(entries, null, 2)
  const source = `// Auto-generated by vite-plugin-exif — do not edit manually\n` +
    `// Re-generated each time the dev server starts or a production build runs.\n\n` +
    `export interface ExifEntry {\n` +
    `  lat?:   number\n` +
    `  lng?:   number\n` +
    `  date?:  string   // YYYY-MM-DD\n` +
    `  make?:  string\n` +
    `  model?: string\n` +
    `}\n\n` +
    `export const rawExifData: Record<string, ExifEntry> = ${body}\n`

  await fs.writeFile(outFile, source, 'utf8')
  console.log(`[vite-plugin-exif] Wrote EXIF data for ${files.length} images → generatedExif.ts`)
}

export function exifPlugin(): Plugin {
  return {
    name: 'exif-extract',
    async buildStart() {
      await extractAndWrite(process.cwd())
    },
  }
}
