#!/usr/bin/env node
/**
 * rename-photos.mjs
 *
 * Renames photo files to SEO-friendly slugs of the form
 *
 *   dulanga-jayawardena-<descriptive-stem>-<year>.<ext>
 *
 * Run modes:
 *   node scripts/rename-photos.mjs            → dry-run, prints plan, no writes
 *   node scripts/rename-photos.mjs --apply    → executes the plan
 *
 * The plan is deterministic given current photoMetadata + EXIF + posts state,
 * so re-running --apply after a successful run is a no-op.
 *
 * What gets touched on --apply:
 *   public/assets/img/<old>             → public/assets/img/<new>          (git mv)
 *   public/assets/img/thumbs/<old>      → public/assets/img/thumbs/<new>   (git mv)
 *   src/data/photoMetadata.ts           → object keys rewritten
 *   src/data/experiences.ts             → /assets/img/<old> paths rewritten
 *   src/data/featuredConfig.ts          → /assets/img/<old> paths rewritten
 *   posts/<slug>.md                     → frontmatter image: + body ![](…) refs
 *
 * NOT touched (regenerated by the next build):
 *   src/data/generatedExif.ts
 *   src/data/generatedPhotoPostLinks.ts
 *
 * Excluded from rename (referenced by static HTML or considered low-value):
 *   profile.jpeg  — used by public/assets/social/*.html OG cards
 */

import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..')
const APPLY = process.argv.includes('--apply')

const NAME_SLUG = 'dulanga-jayawardena'
const IMG_DIR = join(repoRoot, 'public/assets/img')
const THUMB_DIR = join(IMG_DIR, 'thumbs')
const EXCLUDE = new Set(['profile.jpeg'])

/* ─── Read sources ───────────────────────────────────────────────────────── */

const photoMetaSrc = readFileSync(join(repoRoot, 'src/data/photoMetadata.ts'), 'utf8')
const exifSrc = readFileSync(join(repoRoot, 'src/data/generatedExif.ts'), 'utf8')

/** Crude parser — pulls `date` and `title` per filename key. */
function parsePhotoMetadata(src) {
  const out = {}
  const re = /'([^']+)':\s*\{([\s\S]*?)\n\s*\},/g
  let m
  while ((m = re.exec(src)) !== null) {
    const filename = m[1]
    const body = m[2]
    const get = (key) => {
      const r = new RegExp(`${key}:\\s*'((?:[^'\\\\]|\\\\.)*)'`)
      const x = body.match(r)
      return x ? x[1].replace(/\\'/g, "'") : undefined
    }
    out[filename] = { date: get('date'), title: get('title'), location: get('location') }
  }
  return out
}

/** Pull `date` from generated EXIF for a given filename. */
function parseExifDates(src) {
  const out = {}
  const re = /"([^"]+)":\s*\{([\s\S]*?)\n\s*\}/g
  let m
  while ((m = re.exec(src)) !== null) {
    const dateMatch = m[2].match(/"date":\s*"(\d{4}-\d{2}-\d{2})"/)
    if (dateMatch) out[m[1]] = dateMatch[1]
  }
  return out
}

const photoMeta = parsePhotoMetadata(photoMetaSrc)
const exifDates = parseExifDates(exifSrc)

/* ─── Slug helpers ───────────────────────────────────────────────────────── */

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/[''']/g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)
    .replace(/-+$/g, '')
}

/** Strip extension and the YY.MM_ / YY_ prefix. */
function descriptiveStem(filename) {
  const noExt = filename.replace(/\.[^.]+$/, '')
  return noExt.replace(/^\d{2}\.\d{2}_/, '').replace(/^\d{2}_/, '')
}

function extOf(filename) {
  const m = filename.match(/\.[^.]+$/)
  return m ? m[0] : ''
}

function yearFor(filename) {
  // Priority: photoMetadata.date → EXIF date → YY.MM_ filename prefix → null
  const md = photoMeta[filename]?.date
  if (md && /^\d{4}/.test(md)) return md.slice(0, 4)
  const ex = exifDates[filename]
  if (ex && /^\d{4}/.test(ex)) return ex.slice(0, 4)
  const m = filename.match(/^(\d{2})\./)
  if (m) return `20${m[1]}`
  const my = filename.match(/^(\d{2})_/)
  if (my) return `20${my[1]}`
  return null
}

function newNameFor(filename) {
  const stem = slugify(descriptiveStem(filename))
  const year = yearFor(filename)
  const ext = extOf(filename).toLowerCase()
  const parts = [NAME_SLUG, stem, year].filter(Boolean)
  return `${parts.join('-')}${ext}`
}

/* ─── Build the rename plan ──────────────────────────────────────────────── */

const onDisk = readdirSync(IMG_DIR).filter((f) => {
  // Only files (not the thumbs/ directory), only image extensions
  return /\.(jpe?g|png)$/i.test(f)
})

const plan = []     // { old, new, action: 'rename' | 'skip-excluded' | 'skip-noop' | 'conflict' }
const newNames = new Map()  // new -> [old, …] for conflict detection

for (const old of onDisk.sort()) {
  if (EXCLUDE.has(old)) {
    plan.push({ old, new: old, action: 'skip-excluded' })
    continue
  }
  const proposed = newNameFor(old)
  if (proposed === old) {
    plan.push({ old, new: old, action: 'skip-noop' })
    continue
  }
  if (!newNames.has(proposed)) newNames.set(proposed, [])
  newNames.get(proposed).push(old)
  plan.push({ old, new: proposed, action: 'rename' })
}

// Detect collisions
for (const [name, olds] of newNames.entries()) {
  if (olds.length > 1) {
    for (const item of plan) {
      if (item.new === name && item.action === 'rename') item.action = 'conflict'
    }
  }
}

/* ─── Find every reference site that needs string replacement ────────────── */

const REF_FILES = [
  'src/data/photoMetadata.ts',
  'src/data/experiences.ts',
  'src/data/featuredConfig.ts',
  ...readdirSync(join(repoRoot, 'posts')).filter((f) => f.endsWith('.md')).map((f) => `posts/${f}`),
]

function countRefs(filePath, oldName) {
  if (!existsSync(filePath)) return 0
  const src = readFileSync(filePath, 'utf8')
  // Match the bare filename, but only when it's surrounded by non-filename chars
  // (path separator, quote, paren, whitespace, line start/end).
  const escaped = oldName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const re = new RegExp(`(^|[/"'(\\s])${escaped}([)"'\\s]|$)`, 'g')
  return (src.match(re) ?? []).length
}

const refTotals = {}
for (const item of plan.filter((p) => p.action === 'rename')) {
  refTotals[item.old] = {}
  for (const f of REF_FILES) {
    const n = countRefs(join(repoRoot, f), item.old)
    if (n > 0) refTotals[item.old][f] = n
  }
}

/* ─── Print plan ─────────────────────────────────────────────────────────── */

const colW = Math.max(...plan.map((p) => p.old.length)) + 2
console.log(`\n${APPLY ? '🔧 APPLY mode' : '🔍 DRY-RUN'} — rename plan for ${onDisk.length} files\n`)

const groups = {
  rename: plan.filter((p) => p.action === 'rename'),
  conflict: plan.filter((p) => p.action === 'conflict'),
  'skip-excluded': plan.filter((p) => p.action === 'skip-excluded'),
  'skip-noop': plan.filter((p) => p.action === 'skip-noop'),
}

if (groups.conflict.length > 0) {
  console.log('❌ COLLISIONS — these would produce duplicate filenames:')
  for (const item of groups.conflict) {
    console.log(`   ${item.old.padEnd(colW)}→ ${item.new}`)
  }
  console.log('   Resolve by editing photoMetadata or filename stems before applying.\n')
}

console.log(`✓ ${groups.rename.length} renames:`)
for (const item of groups.rename) {
  const refs = refTotals[item.old] ?? {}
  const refSummary = Object.keys(refs).length > 0
    ? ` [refs: ${Object.entries(refs).map(([f, n]) => `${f.split('/').pop()}×${n}`).join(', ')}]`
    : ''
  console.log(`   ${item.old.padEnd(colW)}→ ${item.new}${refSummary}`)
}

if (groups['skip-excluded'].length > 0) {
  console.log(`\n⊘ ${groups['skip-excluded'].length} excluded:`)
  for (const item of groups['skip-excluded']) console.log(`   ${item.old}`)
}

if (groups['skip-noop'].length > 0) {
  console.log(`\n= ${groups['skip-noop'].length} no-op (already match target):`)
  for (const item of groups['skip-noop']) console.log(`   ${item.old}`)
}

if (groups.conflict.length > 0) {
  console.error('\nAborting — resolve collisions first.')
  process.exit(1)
}

if (!APPLY) {
  console.log('\nDry-run complete. Re-run with --apply to execute.')
  process.exit(0)
}

/* ─── Execute ────────────────────────────────────────────────────────────── */

console.log('\nExecuting rename…')

function gitMv(from, to) {
  execFileSync('git', ['mv', from, to], { cwd: repoRoot, stdio: 'pipe' })
}

function rewriteRefs(filePath, items) {
  const abs = join(repoRoot, filePath)
  if (!existsSync(abs)) return 0
  let src = readFileSync(abs, 'utf8')
  let total = 0
  for (const { old, new: nu } of items) {
    const escaped = old.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const re = new RegExp(`(^|[/"'(\\s])${escaped}([)"'\\s]|$)`, 'g')
    src = src.replace(re, (_, a, b) => {
      total += 1
      return `${a}${nu}${b}`
    })
  }
  writeFileSync(abs, src)
  return total
}

// 1. Move files
for (const item of groups.rename) {
  const fromImg = join('public/assets/img', item.old)
  const toImg = join('public/assets/img', item.new)
  gitMv(fromImg, toImg)
  console.log(`  mv ${fromImg} → ${toImg}`)

  const fromThumb = join('public/assets/img/thumbs', item.old)
  if (existsSync(join(repoRoot, fromThumb))) {
    const toThumb = join('public/assets/img/thumbs', item.new)
    gitMv(fromThumb, toThumb)
    console.log(`  mv ${fromThumb} → ${toThumb}`)
  }
}

// 2. Rewrite references
for (const f of REF_FILES) {
  const n = rewriteRefs(f, groups.rename)
  if (n > 0) console.log(`  edit ${f}: ${n} refs`)
}

console.log('\n✓ Rename complete. Run `npm run build` to regenerate generatedExif.ts and generatedPhotoPostLinks.ts.')
