// Auto-generated by vite-plugin-exif — do not edit manually
// Re-generated each time the dev server starts or a production build runs.

export interface ExifEntry {
  lat?:   number
  lng?:   number
  date?:  string   // YYYY-MM-DD
  make?:  string
  model?: string
  title?: string
  description?: string
}

export const rawExifData: Record<string, ExifEntry> = {
  "15.02_moir.jpeg": {
    "date": "2015-06-08",
    "make": "Google",
    "model": "Nexus 5"
  },
  "15.07_edexcel.jpeg": {
    "date": "2015-12-14",
    "make": "NIKON CORPORATION",
    "model": "NIKON D90"
  },
  "16.11_graduation.jpeg": {
    "date": "2016-11-17"
  },
  "18.07_london_bridge.jpeg": {
    "lat": 51.5079,
    "lng": -0.08765833333333332,
    "date": "2018-07-14",
    "make": "Apple",
    "model": "iPhone 7",
    "title": "Following my roommate through London Bridge"
  },
  "18.09_window.jpeg": {
    "date": "2018-09-07",
    "make": "Apple",
    "model": "iPhone 7"
  },
  "18.10_canoe.jpeg": {
    "date": "2018-10-06",
    "make": "LG Electronics",
    "model": "LG-F800L"
  },
  "18.10_roadTest.jpeg": {
    "date": "2018-10-15"
  },
  "18.11_stitching.jpeg": {
    "date": "2018-11-09"
  },
  "18.12_grand_canyon.jpeg": {
    "lat": 36.063288888888884,
    "lng": -112.12353611111111,
    "date": "2018-12-14",
    "make": "Apple",
    "model": "iPhone 7",
    "title": "Strolling through the Grand Canyon with one of my best friends"
  },
  "18.12_yosemite.jpeg": {
    "lat": 37.741280555555555,
    "lng": -119.59198888888888,
    "date": "2018-12-06",
    "make": "Apple",
    "model": "iPhone 7",
    "title": "Chapel",
    "description": "Almost died going off-trail in Yosemite"
  },
  "19.05_hkie.jpeg": {
    "lat": 25.0174,
    "lng": 121.5396
  },
  "20.12_vbrands.jpeg": {
    "date": "2020-11-30",
    "make": "OLYMPUS IMAGING CORP.",
    "model": "E-PL3"
  },
  "22_icc.jpeg": {
    "date": "2022-05-03",
    "make": "Apple",
    "model": "iPhone 13 Pro"
  },
  "23.10_icc.jpeg": {
    "lat": 22.303725,
    "lng": 114.16009444444445,
    "date": "2023-10-09",
    "make": "Apple",
    "model": "iPhone 15 Pro Max"
  },
  "23.12_po_toi.jpeg": {
    "lat": 22.15738888888889,
    "lng": 114.2570361111111,
    "date": "2023-12-10",
    "make": "DJI",
    "model": "FC3582",
    "title": "Po Toi Island",
    "description": "My favorite place to look at the night sky, and second favorite camping spot in Hong Kong"
  },
  "24.06_milky_way.jpeg": {
    "lat": -44.00389444444444,
    "lng": 170.484375,
    "date": "2024-06-30",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Plonked my phone on the sunroof and waited inside",
    "description": "While my iPhone did its 30-second exposure"
  },
  "24.06_tekapo.jpeg": {
    "lat": -44.00486388888889,
    "lng": 170.48062222222222,
    "date": "2024-06-30",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Lake Tekapo"
  },
  "25.01_greenland.jpeg": {
    "lat": 78.08078333333333,
    "lng": -52.25155,
    "date": "2025-02-02",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Greenland"
  },
  "25.04_atacama.jpeg": {
    "lat": -22.53493888888889,
    "lng": -68.039475,
    "date": "2025-04-28",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Three layers of Atacama",
    "description": "Visited the Atacama desert (the driest place on Earth) after a rare rain. It was incredible seeing rows of snowy mountains, desert sand, and a moss-covered lake, all in one view"
  },
  "25.04_easter_island.jpeg": {
    "lat": -27.125611111111112,
    "lng": -109.27727777777778,
    "date": "2025-05-04",
    "make": "Apple",
    "model": "iPhone 15 Pro Max"
  },
  "25.04_torres_del_paine.jpeg": {
    "lat": -50.942299999999996,
    "lng": -72.93674722222222,
    "date": "2025-05-01",
    "make": "Apple",
    "model": "iPhone 15 Pro Max"
  },
  "leaves.jpeg": {
    "date": "2023-03-31",
    "make": "Apple",
    "model": "iPhone 13 Pro"
  },
  "litpak.jpeg": {
    "date": "2018-11-12"
  },
  "pilpil.jpeg": {
    "date": "2025-04-30",
    "make": "Apple",
    "model": "iPhone 13 Pro Max"
  },
  "profile.jpeg": {
    "date": "2022-12-16",
    "make": "Apple",
    "model": "iPhone 13 Pro"
  }
}
