// Auto-generated by vite-plugin-exif — do not edit manually
// Re-generated each time the dev server starts or a production build runs.

export interface ExifEntry {
  lat?:   number
  lng?:   number
  date?:  string   // YYYY-MM-DD
  make?:  string
  model?: string
  title?: string
  description?: string
}

export const rawExifData: Record<string, ExifEntry> = {
  "dulanga-jayawardena-atacama-2025.jpeg": {
    "lat": -22.53493888888889,
    "lng": -68.039475,
    "date": "2025-04-28",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Three layers of Atacama",
    "description": "Visited the Atacama desert (the driest place on Earth) after a rare rain. It was incredible seeing rows of snowy mountains, desert sand, and a moss-covered lake, all in one view"
  },
  "dulanga-jayawardena-canoe-2018.jpeg": {
    "date": "2018-10-06",
    "make": "LG Electronics",
    "model": "LG-F800L"
  },
  "dulanga-jayawardena-easter-island-2025.jpeg": {
    "lat": -27.125611111111112,
    "lng": -109.27727777777778,
    "date": "2025-05-04",
    "make": "Apple",
    "model": "iPhone 15 Pro Max"
  },
  "dulanga-jayawardena-edexcel-2015.jpeg": {
    "date": "2015-12-14",
    "make": "NIKON CORPORATION",
    "model": "NIKON D90"
  },
  "dulanga-jayawardena-graduation-2016.jpeg": {
    "date": "2016-11-17"
  },
  "dulanga-jayawardena-grand-canyon-2018.jpeg": {
    "lat": 36.063288888888884,
    "lng": -112.12353611111111,
    "date": "2018-12-14",
    "make": "Apple",
    "model": "iPhone 7",
    "title": "Strolling through the Grand Canyon with one of my best friends"
  },
  "dulanga-jayawardena-greenland-2025.jpeg": {
    "lat": 78.08078333333333,
    "lng": -52.25155,
    "date": "2025-02-02",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Greenland"
  },
  "dulanga-jayawardena-hkie-2019.jpeg": {
    "lat": 25.0174,
    "lng": 121.5396
  },
  "dulanga-jayawardena-icc-2022.jpeg": {
    "date": "2022-05-03",
    "make": "Apple",
    "model": "iPhone 13 Pro"
  },
  "dulanga-jayawardena-icc-2023.jpeg": {
    "lat": 22.303725,
    "lng": 114.16009444444445,
    "date": "2023-10-09",
    "make": "Apple",
    "model": "iPhone 15 Pro Max"
  },
  "dulanga-jayawardena-kids4kids-2024.jpeg": {
    "lat": 22.322783333333334,
    "lng": 114.15569166666667,
    "date": "2024-05-25",
    "make": "Apple",
    "model": "iPhone 13 Pro Max"
  },
  "dulanga-jayawardena-leaves-2023.jpeg": {
    "date": "2023-03-31",
    "make": "Apple",
    "model": "iPhone 13 Pro"
  },
  "dulanga-jayawardena-litpak-2018.jpeg": {
    "date": "2018-11-12"
  },
  "dulanga-jayawardena-london-bridge-2018.jpeg": {
    "lat": 51.5079,
    "lng": -0.08765833333333332,
    "date": "2018-07-14",
    "make": "Apple",
    "model": "iPhone 7",
    "title": "Following my roommate through London Bridge"
  },
  "dulanga-jayawardena-lucerne-2024.jpeg": {
    "lat": 46.97157777777778,
    "lng": 8.587786111111111,
    "date": "2024-09-19",
    "make": "DJI",
    "model": "DJI Mini 3 Pro",
    "title": "Lucerne"
  },
  "dulanga-jayawardena-malacca-2025.jpeg": {
    "lat": 2.1825055555555553,
    "lng": 102.263,
    "date": "2025-10-20",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Deepavali Celebrations in Malaysia"
  },
  "dulanga-jayawardena-milky-way-2024.jpeg": {
    "lat": -44.00389444444444,
    "lng": 170.484375,
    "date": "2024-06-30",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Plonked my phone on the sunroof and waited inside",
    "description": "While my iPhone did its 30-second exposure"
  },
  "dulanga-jayawardena-moir-2015.jpeg": {
    "date": "2015-06-08",
    "make": "Google",
    "model": "Nexus 5"
  },
  "dulanga-jayawardena-okinawa-2024.jpeg": {
    "date": "2024-01-13",
    "make": "GoPro",
    "model": "HERO8 Black",
    "title": "Okinawa",
    "description": "DCIM\\101GOPRO\\GOPR6794.JPG"
  },
  "dulanga-jayawardena-patagonia-2025.jpeg": {
    "lat": -51.207030555555555,
    "lng": -72.97460277777778,
    "date": "2025-04-29",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Driving into Patagonia way past curfew"
  },
  "dulanga-jayawardena-perth-2025.jpeg": {
    "lat": -31.948219444444444,
    "lng": 115.85842222222222,
    "date": "2025-04-19",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Self-portrait"
  },
  "dulanga-jayawardena-pilpil-2025.jpeg": {
    "date": "2025-04-30",
    "make": "Apple",
    "model": "iPhone 13 Pro Max"
  },
  "dulanga-jayawardena-po-toi-2023.jpeg": {
    "lat": 22.15738888888889,
    "lng": 114.2570361111111,
    "date": "2023-12-10",
    "make": "DJI",
    "model": "DJI Mini 3 Pro",
    "title": "Po Toi Island",
    "description": "My favorite place to look at the night sky, and second favorite camping spot in Hong Kong"
  },
  "dulanga-jayawardena-roadtest-2018.jpeg": {
    "date": "2018-10-15"
  },
  "dulanga-jayawardena-stitching-2018.jpeg": {
    "date": "2018-11-09"
  },
  "dulanga-jayawardena-tekapo-2024.jpeg": {
    "lat": -44.00486388888889,
    "lng": 170.48062222222222,
    "date": "2024-06-30",
    "make": "Apple",
    "model": "iPhone 15 Pro Max",
    "title": "Lake Tekapo"
  },
  "dulanga-jayawardena-torres-del-paine-2025.jpeg": {
    "lat": -50.942299999999996,
    "lng": -72.93674722222222,
    "date": "2025-05-01",
    "make": "Apple",
    "model": "iPhone 15 Pro Max"
  },
  "dulanga-jayawardena-vbrands-2020.jpeg": {
    "date": "2020-11-30",
    "make": "OLYMPUS IMAGING CORP.",
    "model": "E-PL3"
  },
  "dulanga-jayawardena-window-2018.jpeg": {
    "date": "2018-09-07",
    "make": "Apple",
    "model": "iPhone 7"
  },
  "dulanga-jayawardena-yosemite-2018.jpeg": {
    "lat": 37.741280555555555,
    "lng": -119.59198888888888,
    "date": "2018-12-06",
    "make": "Apple",
    "model": "iPhone 7",
    "title": "Chapel",
    "description": "Almost died going off-trail in Yosemite"
  },
  "profile.jpeg": {
    "date": "2025-12-25",
    "make": "Canon",
    "model": "Canon EOS 6D Mark II"
  }
}
