// Auto-generated by vite-plugin-exif — do not edit manually
// Re-generated each time the dev server starts or a production build runs.

export interface GeneratedPhotoPostLink {
  postId: string
  title:  string
}

export const generatedPhotoPostLinks: Record<string, GeneratedPhotoPostLink[]> = {
  "15.02_moir.jpeg": [
    {
      "postId": "2015-07-31-elizabeth-moir",
      "title": "Excelling at Elizabeth Moir School"
    }
  ],
  "15.07_edexcel.jpeg": [
    {
      "postId": "2015-07-31-elizabeth-moir",
      "title": "Excelling at Elizabeth Moir School"
    }
  ],
  "16.11_graduation.jpeg": [
    {
      "postId": "2020-06-30-cuhk-systems-engineering",
      "title": "Studying Systems Engineering at CUHK"
    }
  ],
  "17.12_heatmap.png": [
    {
      "postId": "2017-12-01-restaurant-recommender",
      "title": "Restaurant Recommender — Data-Driven Restaurant Discovery"
    }
  ],
  "18.09_window.jpeg": [
    {
      "postId": "2018-12-01-dartmouth-engineering-exchange",
      "title": "Doing my exchange semester at Dartmouth College"
    }
  ],
  "18.10_canoe.jpeg": [
    {
      "postId": "2018-12-01-dartmouth-engineering-exchange",
      "title": "Doing my exchange semester at Dartmouth College"
    }
  ],
  "18.10_roadTest.jpeg": [
    {
      "postId": "2018-12-01-wearable-safety-backpack",
      "title": "Lit Pak — Designing a Safer, Smarter Backpack for Nighttime Visibility"
    }
  ],
  "18.11_stitching.jpeg": [
    {
      "postId": "2018-12-01-wearable-safety-backpack",
      "title": "Lit Pak — Designing a Safer, Smarter Backpack for Nighttime Visibility"
    }
  ],
  "18.12_cad.png": [
    {
      "postId": "2018-12-01-wearable-safety-backpack",
      "title": "Lit Pak — Designing a Safer, Smarter Backpack for Nighttime Visibility"
    }
  ],
  "19.05_hkie.jpeg": [
    {
      "postId": "2020-06-30-cuhk-systems-engineering",
      "title": "Studying Systems Engineering at CUHK"
    }
  ],
  "20.12_vbrands.jpeg": [
    {
      "postId": "2020-12-31-vbrands",
      "title": "VBrands — Technology Consultant & Digital Operations"
    }
  ],
  "25.04_hongkong.jpeg": [
    {
      "postId": "2025-05-01-morgan-stanley-equity-risk",
      "title": "Building Software for Equity Risk Management at Morgan Stanley"
    }
  ],
  "leaves.jpeg": [
    {
      "postId": "2020-05-31-social-network-opinion-dynamics",
      "title": "Simulating the Spread of Opinions in Social Networks"
    }
  ],
  "litpak.jpeg": [
    {
      "postId": "2018-12-01-wearable-safety-backpack",
      "title": "Lit Pak — Designing a Safer, Smarter Backpack for Nighttime Visibility"
    }
  ],
  "pilpil.jpeg": [
    {
      "postId": "2017-12-01-restaurant-recommender",
      "title": "Restaurant Recommender — Data-Driven Restaurant Discovery"
    }
  ]
}
