// Auto-generated by vite-plugin-exif — do not edit manually
// Re-generated each time the dev server starts or a production build runs.

export interface GeneratedPhotoPostLink {
  postId: string
  title:  string
}

export const generatedPhotoPostLinks: Record<string, GeneratedPhotoPostLink[]> = {
  "dulanga-jayawardena-cad-2018.png": [
    {
      "postId": "2018-12-01-wearable-safety-backpack",
      "title": "Lit Pak — Designing a Safer, Smarter Backpack for Nighttime Visibility"
    }
  ],
  "dulanga-jayawardena-canoe-2018.jpeg": [
    {
      "postId": "2018-12-01-dartmouth-engineering-exchange",
      "title": "Doing my exchange semester at Dartmouth College"
    }
  ],
  "dulanga-jayawardena-edexcel-2015.jpeg": [
    {
      "postId": "2015-07-31-elizabeth-moir",
      "title": "Excelling at Elizabeth Moir School"
    }
  ],
  "dulanga-jayawardena-graduation-2016.jpeg": [
    {
      "postId": "2020-06-30-cuhk-systems-engineering",
      "title": "Studying Systems Engineering at CUHK"
    }
  ],
  "dulanga-jayawardena-heatmap-2017.png": [
    {
      "postId": "2017-12-01-restaurant-recommender",
      "title": "Restaurant Recommender — Data-Driven Restaurant Discovery"
    }
  ],
  "dulanga-jayawardena-hkie-2019.jpeg": [
    {
      "postId": "2020-06-30-cuhk-systems-engineering",
      "title": "Studying Systems Engineering at CUHK"
    }
  ],
  "dulanga-jayawardena-icc-2022.jpeg": [
    {
      "postId": "2025-05-01-morgan-stanley-equity-risk",
      "title": "Building Software for Equity Risk at Morgan Stanley"
    }
  ],
  "dulanga-jayawardena-leaves-2023.jpeg": [
    {
      "postId": "2020-05-31-social-network-opinion-dynamics",
      "title": "Simulating the Spread of Opinions in Social Networks"
    }
  ],
  "dulanga-jayawardena-litpak-2018.jpeg": [
    {
      "postId": "2018-12-01-wearable-safety-backpack",
      "title": "Lit Pak — Designing a Safer, Smarter Backpack for Nighttime Visibility"
    }
  ],
  "dulanga-jayawardena-moir-2015.jpeg": [
    {
      "postId": "2015-07-31-elizabeth-moir",
      "title": "Excelling at Elizabeth Moir School"
    }
  ],
  "dulanga-jayawardena-pilpil-2025.jpeg": [
    {
      "postId": "2017-12-01-restaurant-recommender",
      "title": "Restaurant Recommender — Data-Driven Restaurant Discovery"
    }
  ],
  "dulanga-jayawardena-roadtest-2018.jpeg": [
    {
      "postId": "2018-12-01-wearable-safety-backpack",
      "title": "Lit Pak — Designing a Safer, Smarter Backpack for Nighttime Visibility"
    }
  ],
  "dulanga-jayawardena-stitching-2018.jpeg": [
    {
      "postId": "2018-12-01-wearable-safety-backpack",
      "title": "Lit Pak — Designing a Safer, Smarter Backpack for Nighttime Visibility"
    }
  ],
  "dulanga-jayawardena-vbrands-2020.jpeg": [
    {
      "postId": "2020-12-31-vbrands",
      "title": "VBrands — Technology Consultant & Digital Operations"
    }
  ],
  "dulanga-jayawardena-window-2018.jpeg": [
    {
      "postId": "2018-12-01-dartmouth-engineering-exchange",
      "title": "Doing my exchange semester at Dartmouth College"
    }
  ]
}
