// Auto-generated by vite-plugin-exif — do not edit manually
// Re-generated each time the dev server starts or a production build runs.

export interface ExifEntry {
  lat?:   number
  lng?:   number
  date?:  string   // YYYY-MM-DD
  make?:  string
  model?: string
}

export const rawExifData: Record<string, ExifEntry> = {
  "15.02_moir.jpeg": {
    "date": "2015-06-08"
  },
  "18.09_window.jpeg": {
    "date": "2018-09-07",
    "make": "Apple",
    "model": "iPhone 7"
  },
  "16.11_graduation.jpeg": {
    "date": "2016-11-17"
  },
  "15.07_edexcel.jpeg": {
    "date": "2015-12-14",
    "make": "NIKON CORPORATION",
    "model": "NIKON D90"
  },
  "18.10_roadTest.jpeg": {
    "date": "2018-10-15"
  },
  "18.10_canoe.jpeg": {
    "date": "2018-10-06",
    "make": "LG Electronics",
    "model": "LG-F800L"
  },
  "18.11_stitching.jpeg": {
    "date": "2018-11-09"
  },
  "20.12_vbrands.jpeg": {
    "date": "1899-11-30",
    "make": "OLYMPUS IMAGING CORP.",
    "model": "E-PL3"
  },
  "pilpil.jpeg": {
    "date": "2025-04-30",
    "make": "Apple",
    "model": "iPhone 13 Pro Max"
  },
  "profile.jpeg": {
    "date": "2022-12-16",
    "make": "Apple",
    "model": "iPhone 13 Pro"
  },
  "23.10_icc.jpeg": {
    "lat": 22.303725,
    "lng": 114.16009444444445,
    "date": "2023-10-09",
    "make": "Apple",
    "model": "iPhone 15 Pro Max"
  },
  "leaves.jpeg": {
    "date": "2023-03-31",
    "make": "Apple",
    "model": "iPhone 13 Pro"
  },
  "litpak.jpeg": {
    "date": "2018-11-12"
  },
  "25.04_hongkong.jpeg": {
    "date": "2022-05-03",
    "make": "Apple",
    "model": "iPhone 13 Pro"
  }
}
