// Auto-generated by vite-plugin-exif — do not edit manually

export const imageWidths: Record<string, number[]> = {
  'dulanga-jayawardena-graduation-2016.jpeg': [480, 960, 1280],
  'dulanga-jayawardena-heatmap-2017.png': [480, 960, 1114],
  'dulanga-jayawardena-icc-2022.jpeg': [480, 960, 1280],
  'dulanga-jayawardena-leaves-2023.jpeg': [480, 960, 1277],
  'dulanga-jayawardena-litpak-2018.jpeg': [480, 960],
  'dulanga-jayawardena-moir-2015.jpeg': [480, 960, 1280],
  'dulanga-jayawardena-pilpil-2025.jpeg': [480, 960, 1280],
  'dulanga-jayawardena-vbrands-2020.jpeg': [480, 960, 1440],
  'dulanga-jayawardena-window-2018.jpeg': [480, 960, 1280],
}
